# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
"""added external report to report schedule

Revision ID: 523e4779917c
Revises: d22c2f4036b1
Create Date: 2022-01-28 00:30:00.233684

"""

# revision identifiers, used by Alembic.
revision = '523e4779917c'
down_revision = 'd22c2f4036b1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report_schedule', sa.Column('report_definition_id', sa.Integer(), nullable=True))
    op.drop_index('ix_creation_method', table_name='report_schedule')
    op.create_foreign_key(None, 'report_schedule', 'report_definitions', ['report_definition_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'report_schedule', type_='foreignkey')
    op.create_index('ix_creation_method', 'report_schedule', ['creation_method'], unique=False)
    op.drop_column('report_schedule', 'report_definition_id')
    # ### end Alembic commands ###
