# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
"""Added arjs to reports and alerts

Revision ID: ec596e673c5c
Revises: c88d0c870add
Create Date: 2021-11-03 14:35:26.389624

"""

# revision identifiers, used by Alembic.
revision = 'ec596e673c5c'
down_revision = 'c88d0c870add'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report_schedule', sa.Column('active_report_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'report_schedule', 'active_reports', ['active_report_id'], ['id'])
    op.create_unique_constraint(None, 'report_schedule_user', ['user_id', 'report_schedule_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'report_schedule_user', type_='unique')
    op.drop_constraint(None, 'report_schedule', type_='foreignkey')
    op.drop_column('report_schedule', 'active_report_id')
    # ### end Alembic commands ###
